[project]
name = "os-mcp"
version = "0.1.0"
description = "A Python MCP server that provides access to Ordnance Survey's DataHub APIs."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.18",
    "anthropic>=0.51.0",
    "fastapi>=0.115.12",
    "mcp>=1.9.0",
    "starlette>=0.46.2",
    "uvicorn>=0.34.2",
]
